stages:
  - test

cypress-tests:
  image: cypress/included:13.1.0
  stage: test
  before_script:
    - npm ci
  script:
    - npx cypress run || true
    - npx mochawesome-merge cypress/reports/*.json > cypress/reports/output.json || true
    - npx marge cypress/reports/output.json -f report -o cypress/reports/html || true
  artifacts:
    when: always
    paths:
      - cypress/screenshots
      - cypress/videos
      - cypress/reports/html/report.html
    expire_in: 1 week
