stages:
  - test

cypress-tests:
  image: cypress/browsers:node18.12.0-chrome107-ff107
  stage: test
  script:
    - npm ci
    - npx cypress run
  artifacts:
    when: always
    paths:
      - cypress/videos/
      - cypress/screenshots/
    expire_in: 1 week
