stages:
  - test

cypress-tests:
  image: cypress/included:13.1.0
  stage: test
  script:
    - npm ci
    - npx cypress run
  artifacts:
    when: always
    paths:
      - cypress/videos/
      - cypress/screenshots/
    expire_in: 1 week
